import "../styles/global.css";
import styles from "../styles/home-layout.module.css";
import Navigation from "../components/navigation";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: "%s | NYT Best Seller",
    default: "NYT Best Seller Explorer",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <div className={styles.contents}>{children}</div>
      </body>
    </html>
  );
}
